package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * AlertTypes generated by hbm2java
 */
public class AlertTypes implements java.io.Serializable {

	private long alertTypeId;
	private int displaySeqNo;
	private String description;
	private Set<MonitorsAlertTypes> monitorsAlertTypeses = new HashSet<MonitorsAlertTypes>(
			0);

	public AlertTypes() {
	}

	public AlertTypes(long alertTypeId, int displaySeqNo, String description) {
		this.alertTypeId = alertTypeId;
		this.displaySeqNo = displaySeqNo;
		this.description = description;
	}

	public AlertTypes(long alertTypeId, int displaySeqNo, String description,
			Set<MonitorsAlertTypes> monitorsAlertTypeses) {
		this.alertTypeId = alertTypeId;
		this.displaySeqNo = displaySeqNo;
		this.description = description;
		this.monitorsAlertTypeses = monitorsAlertTypeses;
	}

	public long getAlertTypeId() {
		return this.alertTypeId;
	}

	public void setAlertTypeId(long alertTypeId) {
		this.alertTypeId = alertTypeId;
	}

	public int getDisplaySeqNo() {
		return this.displaySeqNo;
	}

	public void setDisplaySeqNo(int displaySeqNo) {
		this.displaySeqNo = displaySeqNo;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<MonitorsAlertTypes> getMonitorsAlertTypeses() {
		return this.monitorsAlertTypeses;
	}

	public void setMonitorsAlertTypeses(
			Set<MonitorsAlertTypes> monitorsAlertTypeses) {
		this.monitorsAlertTypeses = monitorsAlertTypeses;
	}

}
