package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Alert generated by hbm2java
 */
public class Alert implements java.io.Serializable {

	private long alertId;
	private Alert alert;
	private Monitor monitor;
	private long alertStatusTypeId;
	private long criticalityTypeId;
	private String alertNm;
	private long occurrenceStartTm;
	private Long occurrenceEndTm;
	private String alertText;
	private String comments;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<Alert> alerts = new HashSet<Alert>(0);

	public Alert() {
	}

	public Alert(long alertId, Monitor monitor, long alertStatusTypeId,
			long criticalityTypeId, String alertNm, long occurrenceStartTm) {
		this.alertId = alertId;
		this.monitor = monitor;
		this.alertStatusTypeId = alertStatusTypeId;
		this.criticalityTypeId = criticalityTypeId;
		this.alertNm = alertNm;
		this.occurrenceStartTm = occurrenceStartTm;
	}

	public Alert(long alertId, Alert alert, Monitor monitor,
			long alertStatusTypeId, long criticalityTypeId, String alertNm,
			long occurrenceStartTm, Long occurrenceEndTm, String alertText,
			String comments, Long modifiedTm, String modifiedBy,
			Set<Alert> alerts) {
		this.alertId = alertId;
		this.alert = alert;
		this.monitor = monitor;
		this.alertStatusTypeId = alertStatusTypeId;
		this.criticalityTypeId = criticalityTypeId;
		this.alertNm = alertNm;
		this.occurrenceStartTm = occurrenceStartTm;
		this.occurrenceEndTm = occurrenceEndTm;
		this.alertText = alertText;
		this.comments = comments;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.alerts = alerts;
	}

	public long getAlertId() {
		return this.alertId;
	}

	public void setAlertId(long alertId) {
		this.alertId = alertId;
	}

	public Alert getAlert() {
		return this.alert;
	}

	public void setAlert(Alert alert) {
		this.alert = alert;
	}

	public Monitor getMonitor() {
		return this.monitor;
	}

	public void setMonitor(Monitor monitor) {
		this.monitor = monitor;
	}

	public long getAlertStatusTypeId() {
		return this.alertStatusTypeId;
	}

	public void setAlertStatusTypeId(long alertStatusTypeId) {
		this.alertStatusTypeId = alertStatusTypeId;
	}

	public long getCriticalityTypeId() {
		return this.criticalityTypeId;
	}

	public void setCriticalityTypeId(long criticalityTypeId) {
		this.criticalityTypeId = criticalityTypeId;
	}

	public String getAlertNm() {
		return this.alertNm;
	}

	public void setAlertNm(String alertNm) {
		this.alertNm = alertNm;
	}

	public long getOccurrenceStartTm() {
		return this.occurrenceStartTm;
	}

	public void setOccurrenceStartTm(long occurrenceStartTm) {
		this.occurrenceStartTm = occurrenceStartTm;
	}

	public Long getOccurrenceEndTm() {
		return this.occurrenceEndTm;
	}

	public void setOccurrenceEndTm(Long occurrenceEndTm) {
		this.occurrenceEndTm = occurrenceEndTm;
	}

	public String getAlertText() {
		return this.alertText;
	}

	public void setAlertText(String alertText) {
		this.alertText = alertText;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<Alert> getAlerts() {
		return this.alerts;
	}

	public void setAlerts(Set<Alert> alerts) {
		this.alerts = alerts;
	}

}
