package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private long applicationId;
	private Company company;
	private String applicationType;
	private String applicationNm;
	private String description;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<ApplicationDestination> applicationDestinations = new HashSet<ApplicationDestination>(
			0);

	public Application() {
	}

	public Application(long applicationId, Company company,
			String applicationType, String applicationNm) {
		this.applicationId = applicationId;
		this.company = company;
		this.applicationType = applicationType;
		this.applicationNm = applicationNm;
	}

	public Application(long applicationId, Company company,
			String applicationType, String applicationNm, String description,
			Long modifiedTm, String modifiedBy,
			Set<ApplicationDestination> applicationDestinations) {
		this.applicationId = applicationId;
		this.company = company;
		this.applicationType = applicationType;
		this.applicationNm = applicationNm;
		this.description = description;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.applicationDestinations = applicationDestinations;
	}

	public long getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(long applicationId) {
		this.applicationId = applicationId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationType(String applicationType) {
		this.applicationType = applicationType;
	}

	public String getApplicationNm() {
		return this.applicationNm;
	}

	public void setApplicationNm(String applicationNm) {
		this.applicationNm = applicationNm;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<ApplicationDestination> getApplicationDestinations() {
		return this.applicationDestinations;
	}

	public void setApplicationDestinations(
			Set<ApplicationDestination> applicationDestinations) {
		this.applicationDestinations = applicationDestinations;
	}

}
