package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * ApplicationDestination generated by hbm2java
 */
public class ApplicationDestination implements java.io.Serializable {

	private long applicationDestinationId;
	private Queue queue;
        private long destinationId;
	private Application application;
	private int destinationTypeId;
	private int destinationPurposeTypeId;
	private String destinationNm;
	private Long modifiedTm;
	private String modifiedBy;

	public ApplicationDestination() {
	}

	public ApplicationDestination(long applicationDestinationId, Queue queue,
			Application application, int destinationTypeId,
			int destinationPurposeTypeId) {
		this.applicationDestinationId = applicationDestinationId;
		this.queue = queue;
		this.application = application;
		this.destinationTypeId = destinationTypeId;
		this.destinationPurposeTypeId = destinationPurposeTypeId;
	}

	public ApplicationDestination(long applicationDestinationId, Queue queue,
			Application application, int destinationTypeId,
			int destinationPurposeTypeId, String destinationNm,
			Long modifiedTm, String modifiedBy) {
		this.applicationDestinationId = applicationDestinationId;
		this.queue = queue;
		this.application = application;
		this.destinationTypeId = destinationTypeId;
		this.destinationPurposeTypeId = destinationPurposeTypeId;
		this.destinationNm = destinationNm;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getApplicationDestinationId() {
		return this.applicationDestinationId;
	}

	public void setApplicationDestinationId(long applicationDestinationId) {
		this.applicationDestinationId = applicationDestinationId;
	}

	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	public int getDestinationTypeId() {
		return this.destinationTypeId;
	}

	public void setDestinationTypeId(int destinationTypeId) {
		this.destinationTypeId = destinationTypeId;
	}

	public int getDestinationPurposeTypeId() {
		return this.destinationPurposeTypeId;
	}

	public void setDestinationPurposeTypeId(int destinationPurposeTypeId) {
		this.destinationPurposeTypeId = destinationPurposeTypeId;
	}

	public String getDestinationNm() {
		return this.destinationNm;
	}

	public void setDestinationNm(String destinationNm) {
		this.destinationNm = destinationNm;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

    /**
     * @return the destinationId
     */
    public long getDestinationId() {
        return destinationId;
    }

    /**
     * @param destinationId the destinationId to set
     */
    public void setDestinationId(long destinationId) {
        this.destinationId = destinationId;
    }

    /**
     * @return the queue
     */
    public Queue getQueue() {
        return queue;
    }

    /**
     * @param queue the queue to set
     */
    public void setQueue(Queue queue) {
        this.queue = queue;
    }

}
