package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Channel generated by hbm2java
 */
public class Channel implements java.io.Serializable {

	private long channelId;
	private Qmanager qmanager;
	private String channelNm;
	private int channelTp;
	private int status;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<Monitor> monitors = new HashSet<Monitor>(0);

	public Channel() {
	}

	public Channel(long channelId, Qmanager qmanager, String channelNm,
			int channelTp, int status) {
		this.channelId = channelId;
		this.qmanager = qmanager;
		this.channelNm = channelNm;
		this.channelTp = channelTp;
		this.status = status;
	}

	public Channel(long channelId, Qmanager qmanager, String channelNm,
			int channelTp, int status, Long modifiedTm, String modifiedBy,
			Set<Monitor> monitors) {
		this.channelId = channelId;
		this.qmanager = qmanager;
		this.channelNm = channelNm;
		this.channelTp = channelTp;
		this.status = status;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.monitors = monitors;
	}

	public long getChannelId() {
		return this.channelId;
	}

	public void setChannelId(long channelId) {
		this.channelId = channelId;
	}

	public Qmanager getQmanager() {
		return this.qmanager;
	}

	public void setQmanager(Qmanager qmanager) {
		this.qmanager = qmanager;
	}

	public String getChannelNm() {
		return this.channelNm;
	}

	public void setChannelNm(String channelNm) {
		this.channelNm = channelNm;
	}

	public int getChannelTp() {
		return this.channelTp;
	}

	public void setChannelTp(int channelTp) {
		this.channelTp = channelTp;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<Monitor> getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set<Monitor> monitors) {
		this.monitors = monitors;
	}

}
