package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * CollectionPolicies generated by hbm2java
 */
public class CollectionPolicies implements java.io.Serializable {

	private long collectionPolicyId;
	private long qmanagerId;
	private long intervalTypeId;
	private long intervalVal;
	private int status;
	private String filter;
	private Long modifiedTm;
	private String modifiedBy;

	public CollectionPolicies() {
	}

	public CollectionPolicies(long collectionPolicyId, long qmanagerId,
			long intervalTypeId, long intervalVal, int status) {
		this.collectionPolicyId = collectionPolicyId;
		this.qmanagerId = qmanagerId;
		this.intervalTypeId = intervalTypeId;
		this.intervalVal = intervalVal;
		this.status = status;
	}

	public CollectionPolicies(long collectionPolicyId, long qmanagerId,
			long intervalTypeId, long intervalVal, int status, String filter,
			Long modifiedTm, String modifiedBy) {
		this.collectionPolicyId = collectionPolicyId;
		this.qmanagerId = qmanagerId;
		this.intervalTypeId = intervalTypeId;
		this.intervalVal = intervalVal;
		this.status = status;
		this.filter = filter;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getCollectionPolicyId() {
		return this.collectionPolicyId;
	}

	public void setCollectionPolicyId(long collectionPolicyId) {
		this.collectionPolicyId = collectionPolicyId;
	}

	public long getQmanagerId() {
		return this.qmanagerId;
	}

	public void setQmanagerId(long qmanagerId) {
		this.qmanagerId = qmanagerId;
	}

	public long getIntervalTypeId() {
		return this.intervalTypeId;
	}

	public void setIntervalTypeId(long intervalTypeId) {
		this.intervalTypeId = intervalTypeId;
	}

	public long getIntervalVal() {
		return this.intervalVal;
	}

	public void setIntervalVal(long intervalVal) {
		this.intervalVal = intervalVal;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getFilter() {
		return this.filter;
	}

	public void setFilter(String filter) {
		this.filter = filter;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
