package com.netflexity.qflex.domain;

// Generated Jul 31, 2008 4:30:45 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

	private long companyId;
	private String companyNm;
	private String serialNo;
	private String addr;
	private String city;
	private String state;
	private String zip;
	private String email;
	private String phone;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<Application> applications = new HashSet<Application>(0);
	private Set<Process> processes = new HashSet<Process>(0);
	private Set<Qmanager> qmanagers = new HashSet<Qmanager>(0);
	private Set<Principals> principalses = new HashSet<Principals>(0);
	private Set<Monitor> monitors = new HashSet<Monitor>(0);

	public Company() {
	}

	public Company(long companyId, String companyNm, String serialNo,
			String email) {
		this.companyId = companyId;
		this.companyNm = companyNm;
		this.serialNo = serialNo;
		this.email = email;
	}

	public Company(long companyId, String companyNm, String serialNo,
			String addr, String city, String state, String zip, String email,
			String phone, Long modifiedTm, String modifiedBy,
			Set<Application> applications, Set<Process> processes, Set<Qmanager> qmanagers,
			Set<Principals> principalses, Set<Monitor> monitors) {
		this.companyId = companyId;
		this.companyNm = companyNm;
		this.serialNo = serialNo;
		this.addr = addr;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.email = email;
		this.phone = phone;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.applications = applications;
		this.processes = processes;
		this.qmanagers = qmanagers;
		this.principalses = principalses;
		this.monitors = monitors;
	}

	public long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(long companyId) {
		this.companyId = companyId;
	}

	public String getCompanyNm() {
		return this.companyNm;
	}

	public void setCompanyNm(String companyNm) {
		this.companyNm = companyNm;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<Application> getApplications() {
		return this.applications;
	}

	public void setApplications(Set<Application> applications) {
		this.applications = applications;
	}

	public Set<Process> getProcesses() {
		return this.processes;
	}

	public void setProcesses(Set<Process> processes) {
		this.processes = processes;
	}

	public Set<Qmanager> getQmanagers() {
		return this.qmanagers;
	}

	public void setQmanagers(Set<Qmanager> qmanagers) {
		this.qmanagers = qmanagers;
	}

	public Set<Principals> getPrincipalses() {
		return this.principalses;
	}

	public void setPrincipalses(Set<Principals> principalses) {
		this.principalses = principalses;
	}

	public Set<Monitor> getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set<Monitor> monitors) {
		this.monitors = monitors;
	}

}
