package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * CompressionPolicies generated by hbm2java
 */
public class CompressionPolicies implements java.io.Serializable {

	private long compressionPolicyId;
	private long qmanagerId;
	private long intervalTypeId;
	private long frequencyTypeId;
	private long intervalVal;
	private Long timeOfCompression;
	private int status;
	private Long modifiedTm;
	private String modifiedBy;

	public CompressionPolicies() {
	}

	public CompressionPolicies(long compressionPolicyId, long qmanagerId,
			long intervalTypeId, long frequencyTypeId, long intervalVal,
			int status) {
		this.compressionPolicyId = compressionPolicyId;
		this.qmanagerId = qmanagerId;
		this.intervalTypeId = intervalTypeId;
		this.frequencyTypeId = frequencyTypeId;
		this.intervalVal = intervalVal;
		this.status = status;
	}

	public CompressionPolicies(long compressionPolicyId, long qmanagerId,
			long intervalTypeId, long frequencyTypeId, long intervalVal,
			Long timeOfCompression, int status, Long modifiedTm,
			String modifiedBy) {
		this.compressionPolicyId = compressionPolicyId;
		this.qmanagerId = qmanagerId;
		this.intervalTypeId = intervalTypeId;
		this.frequencyTypeId = frequencyTypeId;
		this.intervalVal = intervalVal;
		this.timeOfCompression = timeOfCompression;
		this.status = status;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getCompressionPolicyId() {
		return this.compressionPolicyId;
	}

	public void setCompressionPolicyId(long compressionPolicyId) {
		this.compressionPolicyId = compressionPolicyId;
	}

	public long getQmanagerId() {
		return this.qmanagerId;
	}

	public void setQmanagerId(long qmanagerId) {
		this.qmanagerId = qmanagerId;
	}

	public long getIntervalTypeId() {
		return this.intervalTypeId;
	}

	public void setIntervalTypeId(long intervalTypeId) {
		this.intervalTypeId = intervalTypeId;
	}

	public long getFrequencyTypeId() {
		return this.frequencyTypeId;
	}

	public void setFrequencyTypeId(long frequencyTypeId) {
		this.frequencyTypeId = frequencyTypeId;
	}

	public long getIntervalVal() {
		return this.intervalVal;
	}

	public void setIntervalVal(long intervalVal) {
		this.intervalVal = intervalVal;
	}

	public Long getTimeOfCompression() {
		return this.timeOfCompression;
	}

	public void setTimeOfCompression(Long timeOfCompression) {
		this.timeOfCompression = timeOfCompression;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
