package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * MessageTypes generated by hbm2java
 */
public class MessageTypes implements java.io.Serializable {

	private long messageTypeId;
	private long trigConditionTypeId;
	private int displaySeqNo;
	private String description;

	public MessageTypes() {
	}

	public MessageTypes(long messageTypeId, long trigConditionTypeId,
			int displaySeqNo, String description) {
		this.messageTypeId = messageTypeId;
		this.trigConditionTypeId = trigConditionTypeId;
		this.displaySeqNo = displaySeqNo;
		this.description = description;
	}

	public long getMessageTypeId() {
		return this.messageTypeId;
	}

	public void setMessageTypeId(long messageTypeId) {
		this.messageTypeId = messageTypeId;
	}

	public long getTrigConditionTypeId() {
		return this.trigConditionTypeId;
	}

	public void setTrigConditionTypeId(long trigConditionTypeId) {
		this.trigConditionTypeId = trigConditionTypeId;
	}

	public int getDisplaySeqNo() {
		return this.displaySeqNo;
	}

	public void setDisplaySeqNo(int displaySeqNo) {
		this.displaySeqNo = displaySeqNo;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
