package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * MessagePurgerPolicies generated by hbm2java
 */
public class MessagePurgerPolicies implements java.io.Serializable {

	private long messagePurgerPolicyId;
	private long queueId;
	private long intervalTypeId;
	private long intervalVal;
	private long purgerIntervalTypeId;
	private long purgerIntervalVal;
	private int status;

	public MessagePurgerPolicies() {
	}

	public MessagePurgerPolicies(long messagePurgerPolicyId, long queueId,
			long intervalTypeId, long intervalVal, long purgerIntervalTypeId,
			long purgerIntervalVal, int status) {
		this.messagePurgerPolicyId = messagePurgerPolicyId;
		this.queueId = queueId;
		this.intervalTypeId = intervalTypeId;
		this.intervalVal = intervalVal;
		this.purgerIntervalTypeId = purgerIntervalTypeId;
		this.purgerIntervalVal = purgerIntervalVal;
		this.status = status;
	}

	public long getMessagePurgerPolicyId() {
		return this.messagePurgerPolicyId;
	}

	public void setMessagePurgerPolicyId(long messagePurgerPolicyId) {
		this.messagePurgerPolicyId = messagePurgerPolicyId;
	}

	public long getQueueId() {
		return this.queueId;
	}

	public void setQueueId(long queueId) {
		this.queueId = queueId;
	}

	public long getIntervalTypeId() {
		return this.intervalTypeId;
	}

	public void setIntervalTypeId(long intervalTypeId) {
		this.intervalTypeId = intervalTypeId;
	}

	public long getIntervalVal() {
		return this.intervalVal;
	}

	public void setIntervalVal(long intervalVal) {
		this.intervalVal = intervalVal;
	}

	public long getPurgerIntervalTypeId() {
		return this.purgerIntervalTypeId;
	}

	public void setPurgerIntervalTypeId(long purgerIntervalTypeId) {
		this.purgerIntervalTypeId = purgerIntervalTypeId;
	}

	public long getPurgerIntervalVal() {
		return this.purgerIntervalVal;
	}

	public void setPurgerIntervalVal(long purgerIntervalVal) {
		this.purgerIntervalVal = purgerIntervalVal;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
