package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * MonitorTemplates generated by hbm2java
 */
public class MonitorTemplates implements java.io.Serializable {

	private long monitorTemplateId;
	private long companyId;
	private long monitorTypeId;
	private long trigConditionTypeId;
	private long criticalityTypeId;
	private String templateNm;
	private int occurrenceInterval;
	private long pollingInterval;
	private Long modifiedTm;
	private String modifiedBy;

	public MonitorTemplates() {
	}

	public MonitorTemplates(long monitorTemplateId, long companyId,
			long monitorTypeId, long trigConditionTypeId,
			long criticalityTypeId, String templateNm, int occurrenceInterval,
			long pollingInterval) {
		this.monitorTemplateId = monitorTemplateId;
		this.companyId = companyId;
		this.monitorTypeId = monitorTypeId;
		this.trigConditionTypeId = trigConditionTypeId;
		this.criticalityTypeId = criticalityTypeId;
		this.templateNm = templateNm;
		this.occurrenceInterval = occurrenceInterval;
		this.pollingInterval = pollingInterval;
	}

	public MonitorTemplates(long monitorTemplateId, long companyId,
			long monitorTypeId, long trigConditionTypeId,
			long criticalityTypeId, String templateNm, int occurrenceInterval,
			long pollingInterval, Long modifiedTm, String modifiedBy) {
		this.monitorTemplateId = monitorTemplateId;
		this.companyId = companyId;
		this.monitorTypeId = monitorTypeId;
		this.trigConditionTypeId = trigConditionTypeId;
		this.criticalityTypeId = criticalityTypeId;
		this.templateNm = templateNm;
		this.occurrenceInterval = occurrenceInterval;
		this.pollingInterval = pollingInterval;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getMonitorTemplateId() {
		return this.monitorTemplateId;
	}

	public void setMonitorTemplateId(long monitorTemplateId) {
		this.monitorTemplateId = monitorTemplateId;
	}

	public long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(long companyId) {
		this.companyId = companyId;
	}

	public long getMonitorTypeId() {
		return this.monitorTypeId;
	}

	public void setMonitorTypeId(long monitorTypeId) {
		this.monitorTypeId = monitorTypeId;
	}

	public long getTrigConditionTypeId() {
		return this.trigConditionTypeId;
	}

	public void setTrigConditionTypeId(long trigConditionTypeId) {
		this.trigConditionTypeId = trigConditionTypeId;
	}

	public long getCriticalityTypeId() {
		return this.criticalityTypeId;
	}

	public void setCriticalityTypeId(long criticalityTypeId) {
		this.criticalityTypeId = criticalityTypeId;
	}

	public String getTemplateNm() {
		return this.templateNm;
	}

	public void setTemplateNm(String templateNm) {
		this.templateNm = templateNm;
	}

	public int getOccurrenceInterval() {
		return this.occurrenceInterval;
	}

	public void setOccurrenceInterval(int occurrenceInterval) {
		this.occurrenceInterval = occurrenceInterval;
	}

	public long getPollingInterval() {
		return this.pollingInterval;
	}

	public void setPollingInterval(long pollingInterval) {
		this.pollingInterval = pollingInterval;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
