package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * MonitorsAlertTypes generated by hbm2java
 */
public class MonitorsAlertTypes implements java.io.Serializable {

	private long monitorsAlertTypesId;
	private AlertTypes alertTypes;
	private Monitor monitor;
	private Long monitorTemplateId;
	private Long modifiedTm;
	private String modifiedBy;

	public MonitorsAlertTypes() {
	}

	public MonitorsAlertTypes(long monitorsAlertTypesId, AlertTypes alertTypes) {
		this.monitorsAlertTypesId = monitorsAlertTypesId;
		this.alertTypes = alertTypes;
	}

	public MonitorsAlertTypes(long monitorsAlertTypesId, AlertTypes alertTypes,
			Monitor monitor, Long monitorTemplateId, Long modifiedTm,
			String modifiedBy) {
		this.monitorsAlertTypesId = monitorsAlertTypesId;
		this.alertTypes = alertTypes;
		this.monitor = monitor;
		this.monitorTemplateId = monitorTemplateId;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getMonitorsAlertTypesId() {
		return this.monitorsAlertTypesId;
	}

	public void setMonitorsAlertTypesId(long monitorsAlertTypesId) {
		this.monitorsAlertTypesId = monitorsAlertTypesId;
	}

	public AlertTypes getAlertTypes() {
		return this.alertTypes;
	}

	public void setAlertTypes(AlertTypes alertTypes) {
		this.alertTypes = alertTypes;
	}

	public Monitor getMonitor() {
		return this.monitor;
	}

	public void setMonitor(Monitor monitor) {
		this.monitor = monitor;
	}

	public Long getMonitorTemplateId() {
		return this.monitorTemplateId;
	}

	public void setMonitorTemplateId(Long monitorTemplateId) {
		this.monitorTemplateId = monitorTemplateId;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
