package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Monitor generated by hbm2java
 */
public class Monitor implements java.io.Serializable {

	private long monitorId;

        private long monitoredObjectId;
//	private Qmanager qmanagerByMonitorObjectId;
	private Channel channel;
	private Qmanager qmanagerByQmanagerId;
	private Company company;
	private Queue queue;
	private long monitorTypeId;
	private long trigConditionTypeId;
	private Long trigConditionParam;
	private long criticalityTypeId;
	private String monitorNm;
	private String messageText;
	private String recoveryText;
	private int occurrenceInterval;
	private long pollingInterval;
	private String logFile;
	private int status;
	private String emailList;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<MonitorsAlertTypes> monitorsAlertTypeses = new HashSet<MonitorsAlertTypes>(
			0);
	private Set<MonitorsPollingPolicies> monitorsPollingPolicieses = new HashSet<MonitorsPollingPolicies>(
			0);
	private Set<MonitorsRecoveryActions> monitorsRecoveryActionses = new HashSet<MonitorsRecoveryActions>(
			0);
	private Set<Alert> alerts = new HashSet<Alert>(0);

	public Monitor() {
	}

	public Monitor(long monitorId, long monitoredObjectId,
			Channel channel, Qmanager qmanagerByQmanagerId, Company company,
			Queue queue, long monitorTypeId, long trigConditionTypeId,
			long criticalityTypeId, String monitorNm, String messageText,
			String recoveryText, int occurrenceInterval, long pollingInterval,
			int status) {
		this.monitorId = monitorId;
		this.monitoredObjectId = monitoredObjectId;
		this.channel = channel;
		this.qmanagerByQmanagerId = qmanagerByQmanagerId;
		this.company = company;
		this.queue = queue;
		this.monitorTypeId = monitorTypeId;
		this.trigConditionTypeId = trigConditionTypeId;
		this.criticalityTypeId = criticalityTypeId;
		this.monitorNm = monitorNm;
		this.messageText = messageText;
		this.recoveryText = recoveryText;
		this.occurrenceInterval = occurrenceInterval;
		this.pollingInterval = pollingInterval;
		this.status = status;
	}

	public Monitor(long monitorId, long monitoredObjectId,
			Channel channel, Qmanager qmanagerByQmanagerId, Company company,
			Queue queue, long monitorTypeId, long trigConditionTypeId,
			Long trigConditionParam, long criticalityTypeId, String monitorNm,
			String messageText, String recoveryText, int occurrenceInterval,
			long pollingInterval, String logFile, int status, String emailList,
			Long modifiedTm, String modifiedBy,
			Set<MonitorsAlertTypes> monitorsAlertTypeses,
			Set<MonitorsPollingPolicies> monitorsPollingPolicieses,
			Set<MonitorsRecoveryActions> monitorsRecoveryActionses,
			Set<Alert> alerts) {
		this.monitorId = monitorId;
		this.monitoredObjectId = monitoredObjectId;
		this.channel = channel;
		this.qmanagerByQmanagerId = qmanagerByQmanagerId;
		this.company = company;
		this.queue = queue;
		this.monitorTypeId = monitorTypeId;
		this.trigConditionTypeId = trigConditionTypeId;
		this.trigConditionParam = trigConditionParam;
		this.criticalityTypeId = criticalityTypeId;
		this.monitorNm = monitorNm;
		this.messageText = messageText;
		this.recoveryText = recoveryText;
		this.occurrenceInterval = occurrenceInterval;
		this.pollingInterval = pollingInterval;
		this.logFile = logFile;
		this.status = status;
		this.emailList = emailList;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.monitorsAlertTypeses = monitorsAlertTypeses;
		this.monitorsPollingPolicieses = monitorsPollingPolicieses;
		this.monitorsRecoveryActionses = monitorsRecoveryActionses;
		this.alerts = alerts;
	}

	public long getMonitorId() {
		return this.monitorId;
	}

	public void setMonitorId(long monitorId) {
		this.monitorId = monitorId;
	}

//	public Qmanager getQmanagerByMonitorObjectId() {
//		return this.qmanagerByMonitorObjectId;
//	}
//
//	public void setQmanagerByMonitorObjectId(Qmanager qmanagerByMonitorObjectId) {
//		this.qmanagerByMonitorObjectId = qmanagerByMonitorObjectId;
//	}

	public Channel getChannel() {
		return this.channel;
	}

	public void setChannel(Channel channel) {
		this.channel = channel;
	}

	public Qmanager getQmanagerByQmanagerId() {
		return this.qmanagerByQmanagerId;
	}

	public void setQmanagerByQmanagerId(Qmanager qmanagerByQmanagerId) {
		this.qmanagerByQmanagerId = qmanagerByQmanagerId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Queue getQueue() {
		return this.queue;
	}

	public void setQueue(Queue queue) {
		this.queue = queue;
	}

	public long getMonitorTypeId() {
		return this.monitorTypeId;
	}

	public void setMonitorTypeId(long monitorTypeId) {
		this.monitorTypeId = monitorTypeId;
	}

	public long getTrigConditionTypeId() {
		return this.trigConditionTypeId;
	}

	public void setTrigConditionTypeId(long trigConditionTypeId) {
		this.trigConditionTypeId = trigConditionTypeId;
	}

	public Long getTrigConditionParam() {
		return this.trigConditionParam;
	}

	public void setTrigConditionParam(Long trigConditionParam) {
		this.trigConditionParam = trigConditionParam;
	}

	public long getCriticalityTypeId() {
		return this.criticalityTypeId;
	}

	public void setCriticalityTypeId(long criticalityTypeId) {
		this.criticalityTypeId = criticalityTypeId;
	}

	public String getMonitorNm() {
		return this.monitorNm;
	}

	public void setMonitorNm(String monitorNm) {
		this.monitorNm = monitorNm;
	}

	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	public String getRecoveryText() {
		return this.recoveryText;
	}

	public void setRecoveryText(String recoveryText) {
		this.recoveryText = recoveryText;
	}

	public int getOccurrenceInterval() {
		return this.occurrenceInterval;
	}

	public void setOccurrenceInterval(int occurrenceInterval) {
		this.occurrenceInterval = occurrenceInterval;
	}

	public long getPollingInterval() {
		return this.pollingInterval;
	}

	public void setPollingInterval(long pollingInterval) {
		this.pollingInterval = pollingInterval;
	}

	public String getLogFile() {
		return this.logFile;
	}

	public void setLogFile(String logFile) {
		this.logFile = logFile;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getEmailList() {
		return this.emailList;
	}

	public void setEmailList(String emailList) {
		this.emailList = emailList;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<MonitorsAlertTypes> getMonitorsAlertTypeses() {
		return this.monitorsAlertTypeses;
	}

	public void setMonitorsAlertTypeses(
			Set<MonitorsAlertTypes> monitorsAlertTypeses) {
		this.monitorsAlertTypeses = monitorsAlertTypeses;
	}

	public Set<MonitorsPollingPolicies> getMonitorsPollingPolicieses() {
		return this.monitorsPollingPolicieses;
	}

	public void setMonitorsPollingPolicieses(
			Set<MonitorsPollingPolicies> monitorsPollingPolicieses) {
		this.monitorsPollingPolicieses = monitorsPollingPolicieses;
	}

	public Set<MonitorsRecoveryActions> getMonitorsRecoveryActionses() {
		return this.monitorsRecoveryActionses;
	}

	public void setMonitorsRecoveryActionses(
			Set<MonitorsRecoveryActions> monitorsRecoveryActionses) {
		this.monitorsRecoveryActionses = monitorsRecoveryActionses;
	}

	public Set<Alert> getAlerts() {
		return this.alerts;
	}

	public void setAlerts(Set<Alert> alerts) {
		this.alerts = alerts;
	}

    /**
     * @return the monitoredObjectId
     */
    public long getMonitoredObjectId() {
        return monitoredObjectId;
    }

    /**
     * @param monitoredObjectId the monitoredObjectId to set
     */
    public void setMonitoredObjectId(long monitoredObjectId) {
        this.monitoredObjectId = monitoredObjectId;
    }

}
