package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * MonitorsPollingPolicies generated by hbm2java
 */
public class MonitorsPollingPolicies implements java.io.Serializable {

	private long monitorsPollingPoliciesId;
	private Monitor monitor;
	private PollingPolicies pollingPolicies;
	private Long monitorTemplateId;
	private Long modifiedTm;
	private String modifiedBy;

	public MonitorsPollingPolicies() {
	}

	public MonitorsPollingPolicies(long monitorsPollingPoliciesId,
			PollingPolicies pollingPolicies) {
		this.monitorsPollingPoliciesId = monitorsPollingPoliciesId;
		this.pollingPolicies = pollingPolicies;
	}

	public MonitorsPollingPolicies(long monitorsPollingPoliciesId,
			Monitor monitor, PollingPolicies pollingPolicies,
			Long monitorTemplateId, Long modifiedTm, String modifiedBy) {
		this.monitorsPollingPoliciesId = monitorsPollingPoliciesId;
		this.monitor = monitor;
		this.pollingPolicies = pollingPolicies;
		this.monitorTemplateId = monitorTemplateId;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getMonitorsPollingPoliciesId() {
		return this.monitorsPollingPoliciesId;
	}

	public void setMonitorsPollingPoliciesId(long monitorsPollingPoliciesId) {
		this.monitorsPollingPoliciesId = monitorsPollingPoliciesId;
	}

	public Monitor getMonitor() {
		return this.monitor;
	}

	public void setMonitor(Monitor monitor) {
		this.monitor = monitor;
	}

	public PollingPolicies getPollingPolicies() {
		return this.pollingPolicies;
	}

	public void setPollingPolicies(PollingPolicies pollingPolicies) {
		this.pollingPolicies = pollingPolicies;
	}

	public Long getMonitorTemplateId() {
		return this.monitorTemplateId;
	}

	public void setMonitorTemplateId(Long monitorTemplateId) {
		this.monitorTemplateId = monitorTemplateId;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
