package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * MonitorsRecoveryActions generated by hbm2java
 */
public class MonitorsRecoveryActions implements java.io.Serializable {

	private long monitorsRecoveryActionId;
	private Monitor monitor;
	private RecoveryActions recoveryActions;
	private Long monitorTemplateId;
	private Long modifiedTm;
	private String modifiedBy;

	public MonitorsRecoveryActions() {
	}

	public MonitorsRecoveryActions(long monitorsRecoveryActionId,
			RecoveryActions recoveryActions) {
		this.monitorsRecoveryActionId = monitorsRecoveryActionId;
		this.recoveryActions = recoveryActions;
	}

	public MonitorsRecoveryActions(long monitorsRecoveryActionId,
			Monitor monitor, RecoveryActions recoveryActions,
			Long monitorTemplateId, Long modifiedTm, String modifiedBy) {
		this.monitorsRecoveryActionId = monitorsRecoveryActionId;
		this.monitor = monitor;
		this.recoveryActions = recoveryActions;
		this.monitorTemplateId = monitorTemplateId;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getMonitorsRecoveryActionId() {
		return this.monitorsRecoveryActionId;
	}

	public void setMonitorsRecoveryActionId(long monitorsRecoveryActionId) {
		this.monitorsRecoveryActionId = monitorsRecoveryActionId;
	}

	public Monitor getMonitor() {
		return this.monitor;
	}

	public void setMonitor(Monitor monitor) {
		this.monitor = monitor;
	}

	public RecoveryActions getRecoveryActions() {
		return this.recoveryActions;
	}

	public void setRecoveryActions(RecoveryActions recoveryActions) {
		this.recoveryActions = recoveryActions;
	}

	public Long getMonitorTemplateId() {
		return this.monitorTemplateId;
	}

	public void setMonitorTemplateId(Long monitorTemplateId) {
		this.monitorTemplateId = monitorTemplateId;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
