package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * PollingPolicies generated by hbm2java
 */
public class PollingPolicies implements java.io.Serializable {

	private long pollingPolicyId;
	private String pollingPolicyNm;
	private long companyId;
	private String minutes;
	private String hours;
	private String daysOfWeek;
	private String daysOfMonth;
	private String months;
	private String seconds;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<MonitorsPollingPolicies> monitorsPollingPolicieses = new HashSet<MonitorsPollingPolicies>(
			0);
	
	public PollingPolicies() {
	}

	public PollingPolicies(long pollingPolicyId, String pollingPolicyNm,
			long companyId, String minutes, String hours, String daysOfWeek,
			String daysOfMonth, String months, String seconds) {
		this.pollingPolicyId = pollingPolicyId;
		this.pollingPolicyNm = pollingPolicyNm;
		this.companyId = companyId;
		this.minutes = minutes;
		this.hours = hours;
		this.daysOfWeek = daysOfWeek;
		this.daysOfMonth = daysOfMonth;
		this.months = months;
		this.seconds = seconds;
	}

	public PollingPolicies(long pollingPolicyId, String pollingPolicyNm,
			long companyId, String minutes, String hours, String daysOfWeek,
			String daysOfMonth, String months, String seconds, Long modifiedTm,
			String modifiedBy,
			Set<MonitorsPollingPolicies> monitorsPollingPolicieses) {
		this.pollingPolicyId = pollingPolicyId;
		this.pollingPolicyNm = pollingPolicyNm;
		this.companyId = companyId;
		this.minutes = minutes;
		this.hours = hours;
		this.daysOfWeek = daysOfWeek;
		this.daysOfMonth = daysOfMonth;
		this.months = months;
		this.seconds = seconds;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.monitorsPollingPolicieses = monitorsPollingPolicieses;
	}

	public long getPollingPolicyId() {
		return this.pollingPolicyId;
	}

	public void setPollingPolicyId(long pollingPolicyId) {
		this.pollingPolicyId = pollingPolicyId;
	}

	public String getPollingPolicyNm() {
		return this.pollingPolicyNm;
	}

	public void setPollingPolicyNm(String pollingPolicyNm) {
		this.pollingPolicyNm = pollingPolicyNm;
	}

	public long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(long companyId) {
		this.companyId = companyId;
	}

	public String getMinutes() {
		return this.minutes;
	}

	public void setMinutes(String minutes) {
		this.minutes = minutes;
	}

	public String getHours() {
		return this.hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	public String getDaysOfWeek() {
		return this.daysOfWeek;
	}

	public void setDaysOfWeek(String daysOfWeek) {
		this.daysOfWeek = daysOfWeek;
	}

	public String getDaysOfMonth() {
		return this.daysOfMonth;
	}

	public void setDaysOfMonth(String daysOfMonth) {
		this.daysOfMonth = daysOfMonth;
	}

	public String getMonths() {
		return this.months;
	}

	public void setMonths(String months) {
		this.months = months;
	}

	public String getSeconds() {
		return this.seconds;
	}

	public void setSeconds(String seconds) {
		this.seconds = seconds;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<MonitorsPollingPolicies> getMonitorsPollingPolicieses() {
		return this.monitorsPollingPolicieses;
	}

	public void setMonitorsPollingPolicieses(
			Set<MonitorsPollingPolicies> monitorsPollingPolicieses) {
		this.monitorsPollingPolicieses = monitorsPollingPolicieses;
	}
}
