package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * Principals generated by hbm2java
 */
public class Principals implements java.io.Serializable {

	private long principalId;
	private Company company;
	private String principalNm;
	private String username;
	private String password;
	private String role;
	private String email;
	private String phone;
	private Long modifiedTm;
	private String modifiedBy;

	public Principals() {
	}

	public Principals(long principalId, Company company, String principalNm,
			String username, String password, String role, String email) {
		this.principalId = principalId;
		this.company = company;
		this.principalNm = principalNm;
		this.username = username;
		this.password = password;
		this.role = role;
		this.email = email;
	}

	public Principals(long principalId, Company company, String principalNm,
			String username, String password, String role, String email,
			String phone, Long modifiedTm, String modifiedBy) {
		this.principalId = principalId;
		this.company = company;
		this.principalNm = principalNm;
		this.username = username;
		this.password = password;
		this.role = role;
		this.email = email;
		this.phone = phone;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getPrincipalId() {
		return this.principalId;
	}

	public void setPrincipalId(long principalId) {
		this.principalId = principalId;
	}

	/**
	 * @return the company
	 */
	public Company getCompany() {
		return company;
	}

	/**
	 * @param company the company to set
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	public String getPrincipalNm() {
		return this.principalNm;
	}

	public void setPrincipalNm(String principalNm) {
		this.principalNm = principalNm;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
