package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * QflexProperties generated by hbm2java
 */
public class QflexProperties implements java.io.Serializable {

	private long qflexPropertyId;
	private long companyId;
	private byte propertyType;
	private String propertyNm;
	private String propertyVal;
	private Long modifiedTm;
	private String modifiedBy;

	public QflexProperties() {
	}

	public QflexProperties(long qflexPropertyId, long companyId,
			byte propertyType, String propertyNm) {
		this.qflexPropertyId = qflexPropertyId;
		this.companyId = companyId;
		this.propertyType = propertyType;
		this.propertyNm = propertyNm;
	}

	public QflexProperties(long qflexPropertyId, long companyId,
			byte propertyType, String propertyNm, String propertyVal,
			Long modifiedTm, String modifiedBy) {
		this.qflexPropertyId = qflexPropertyId;
		this.companyId = companyId;
		this.propertyType = propertyType;
		this.propertyNm = propertyNm;
		this.propertyVal = propertyVal;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getQflexPropertyId() {
		return this.qflexPropertyId;
	}

	public void setQflexPropertyId(long qflexPropertyId) {
		this.qflexPropertyId = qflexPropertyId;
	}

	public long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(long companyId) {
		this.companyId = companyId;
	}

	public byte getPropertyType() {
		return this.propertyType;
	}

	public void setPropertyType(byte propertyType) {
		this.propertyType = propertyType;
	}

	public String getPropertyNm() {
		return this.propertyNm;
	}

	public void setPropertyNm(String propertyNm) {
		this.propertyNm = propertyNm;
	}

	public String getPropertyVal() {
		return this.propertyVal;
	}

	public void setPropertyVal(String propertyVal) {
		this.propertyVal = propertyVal;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
