package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Qmanager generated by hbm2java
 */
public class Qmanager implements java.io.Serializable {

	private long qmanagerId;
	private Company company;
	private int status;
	private String qmanagerNm;
	private String qmanagerAlias;
	private String hostNm;
	private String hostDataRoot;
	private String hostUser;
	private String hostPwd;
	private String channelNm;
	private int port;
	private String commandServerQname;
	private String commandServerReplyQueue;
	private String os;
	private String osVersion;
	private String mqVersion;
	private String sslKeystore;
	private String sslKeystorePwd;
	private String sslTruststore;
	private String sslTruststorePwd;
	private String sslCipherSpec;
	private String sslPeerNm;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<Monitor> monitorsForMonitorObjectId = new HashSet<Monitor>(0);
	private Set<Monitor> monitorsForQmanagerId = new HashSet<Monitor>(0);
	private Set<Queue> queues = new HashSet<Queue>(0);
	private Set<Channel> channels = new HashSet<Channel>(0);

	public Qmanager() {
	}

	public Qmanager(long qmanagerId, Company company, int status,
			String qmanagerNm, String hostNm, String channelNm, int port) {
		this.qmanagerId = qmanagerId;
		this.company = company;
		this.status = status;
		this.qmanagerNm = qmanagerNm;
		this.hostNm = hostNm;
		this.channelNm = channelNm;
		this.port = port;
	}

	public Qmanager(long qmanagerId, Company company, int status,
			String qmanagerNm, String qmanagerAlias, String hostNm,
			String hostDataRoot, String hostUser, String hostPwd,
			String channelNm, int port, String commandServerQname,
			String commandServerReplyQueue, String os, String osVersion,
			String mqVersion, String sslKeystore, String sslKeystorePwd,
			String sslTruststore, String sslTruststorePwd,
			String sslCipherSpec, String sslPeerNm, Long modifiedTm,
			String modifiedBy, Set<Monitor> monitorsForMonitorObjectId,
			Set<Monitor> monitorsForQmanagerId, Set<Queue> queues,
			Set<Channel> channels) {
		this.qmanagerId = qmanagerId;
		this.company = company;
		this.status = status;
		this.qmanagerNm = qmanagerNm;
		this.qmanagerAlias = qmanagerAlias;
		this.hostNm = hostNm;
		this.hostDataRoot = hostDataRoot;
		this.hostUser = hostUser;
		this.hostPwd = hostPwd;
		this.channelNm = channelNm;
		this.port = port;
		this.commandServerQname = commandServerQname;
		this.commandServerReplyQueue = commandServerReplyQueue;
		this.os = os;
		this.osVersion = osVersion;
		this.mqVersion = mqVersion;
		this.sslKeystore = sslKeystore;
		this.sslKeystorePwd = sslKeystorePwd;
		this.sslTruststore = sslTruststore;
		this.sslTruststorePwd = sslTruststorePwd;
		this.sslCipherSpec = sslCipherSpec;
		this.sslPeerNm = sslPeerNm;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.monitorsForMonitorObjectId = monitorsForMonitorObjectId;
		this.monitorsForQmanagerId = monitorsForQmanagerId;
		this.queues = queues;
		this.channels = channels;
	}

	public long getQmanagerId() {
		return this.qmanagerId;
	}

	public void setQmanagerId(long qmanagerId) {
		this.qmanagerId = qmanagerId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getQmanagerNm() {
		return this.qmanagerNm;
	}

	public void setQmanagerNm(String qmanagerNm) {
		this.qmanagerNm = qmanagerNm;
	}

	public String getQmanagerAlias() {
		return this.qmanagerAlias;
	}

	public void setQmanagerAlias(String qmanagerAlias) {
		this.qmanagerAlias = qmanagerAlias;
	}

	public String getHostNm() {
		return this.hostNm;
	}

	public void setHostNm(String hostNm) {
		this.hostNm = hostNm;
	}

	public String getHostDataRoot() {
		return this.hostDataRoot;
	}

	public void setHostDataRoot(String hostDataRoot) {
		this.hostDataRoot = hostDataRoot;
	}

	public String getHostUser() {
		return this.hostUser;
	}

	public void setHostUser(String hostUser) {
		this.hostUser = hostUser;
	}

	public String getHostPwd() {
		return this.hostPwd;
	}

	public void setHostPwd(String hostPwd) {
		this.hostPwd = hostPwd;
	}

	public String getChannelNm() {
		return this.channelNm;
	}

	public void setChannelNm(String channelNm) {
		this.channelNm = channelNm;
	}

	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public String getCommandServerQname() {
		return this.commandServerQname;
	}

	public void setCommandServerQname(String commandServerQname) {
		this.commandServerQname = commandServerQname;
	}

	public String getCommandServerReplyQueue() {
		return this.commandServerReplyQueue;
	}

	public void setCommandServerReplyQueue(String commandServerReplyQueue) {
		this.commandServerReplyQueue = commandServerReplyQueue;
	}

	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getOsVersion() {
		return this.osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	public String getMqVersion() {
		return this.mqVersion;
	}

	public void setMqVersion(String mqVersion) {
		this.mqVersion = mqVersion;
	}

	public String getSslKeystore() {
		return this.sslKeystore;
	}

	public void setSslKeystore(String sslKeystore) {
		this.sslKeystore = sslKeystore;
	}

	public String getSslKeystorePwd() {
		return this.sslKeystorePwd;
	}

	public void setSslKeystorePwd(String sslKeystorePwd) {
		this.sslKeystorePwd = sslKeystorePwd;
	}

	public String getSslTruststore() {
		return this.sslTruststore;
	}

	public void setSslTruststore(String sslTruststore) {
		this.sslTruststore = sslTruststore;
	}

	public String getSslTruststorePwd() {
		return this.sslTruststorePwd;
	}

	public void setSslTruststorePwd(String sslTruststorePwd) {
		this.sslTruststorePwd = sslTruststorePwd;
	}

	public String getSslCipherSpec() {
		return this.sslCipherSpec;
	}

	public void setSslCipherSpec(String sslCipherSpec) {
		this.sslCipherSpec = sslCipherSpec;
	}

	public String getSslPeerNm() {
		return this.sslPeerNm;
	}

	public void setSslPeerNm(String sslPeerNm) {
		this.sslPeerNm = sslPeerNm;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<Monitor> getMonitorsForMonitorObjectId() {
		return this.monitorsForMonitorObjectId;
	}

	public void setMonitorsForMonitorObjectId(
			Set<Monitor> monitorsForMonitorObjectId) {
		this.monitorsForMonitorObjectId = monitorsForMonitorObjectId;
	}

	public Set<Monitor> getMonitorsForQmanagerId() {
		return this.monitorsForQmanagerId;
	}

	public void setMonitorsForQmanagerId(Set<Monitor> monitorsForQmanagerId) {
		this.monitorsForQmanagerId = monitorsForQmanagerId;
	}

	public Set<Queue> getQueues() {
		return this.queues;
	}

	public void setQueues(Set<Queue> queues) {
		this.queues = queues;
	}

	public Set<Channel> getChannels() {
		return this.channels;
	}

	public void setChannels(Set<Channel> channels) {
		this.channels = channels;
	}

}
