package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * QueueStatsIdleness generated by hbm2java
 */
public class QueueStatsIdleness implements java.io.Serializable {

	private long queueStatsIdlenessId;
	private long qmanagerId;
	private long idleStartTm;
	private long idleEndTm;
	private long idleReasonTypeId;
	private int status;
	private Long modifiedTm;
	private String modifiedBy;

	public QueueStatsIdleness() {
	}

	public QueueStatsIdleness(long queueStatsIdlenessId, long qmanagerId,
			long idleStartTm, long idleEndTm, long idleReasonTypeId, int status) {
		this.queueStatsIdlenessId = queueStatsIdlenessId;
		this.qmanagerId = qmanagerId;
		this.idleStartTm = idleStartTm;
		this.idleEndTm = idleEndTm;
		this.idleReasonTypeId = idleReasonTypeId;
		this.status = status;
	}

	public QueueStatsIdleness(long queueStatsIdlenessId, long qmanagerId,
			long idleStartTm, long idleEndTm, long idleReasonTypeId,
			int status, Long modifiedTm, String modifiedBy) {
		this.queueStatsIdlenessId = queueStatsIdlenessId;
		this.qmanagerId = qmanagerId;
		this.idleStartTm = idleStartTm;
		this.idleEndTm = idleEndTm;
		this.idleReasonTypeId = idleReasonTypeId;
		this.status = status;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getQueueStatsIdlenessId() {
		return this.queueStatsIdlenessId;
	}

	public void setQueueStatsIdlenessId(long queueStatsIdlenessId) {
		this.queueStatsIdlenessId = queueStatsIdlenessId;
	}

	public long getQmanagerId() {
		return this.qmanagerId;
	}

	public void setQmanagerId(long qmanagerId) {
		this.qmanagerId = qmanagerId;
	}

	public long getIdleStartTm() {
		return this.idleStartTm;
	}

	public void setIdleStartTm(long idleStartTm) {
		this.idleStartTm = idleStartTm;
	}

	public long getIdleEndTm() {
		return this.idleEndTm;
	}

	public void setIdleEndTm(long idleEndTm) {
		this.idleEndTm = idleEndTm;
	}

	public long getIdleReasonTypeId() {
		return this.idleReasonTypeId;
	}

	public void setIdleReasonTypeId(long idleReasonTypeId) {
		this.idleReasonTypeId = idleReasonTypeId;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
