package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * RecoveryActions generated by hbm2java
 */
public class RecoveryActions implements java.io.Serializable {

	private long recoveryActionId;
	private long recoveryActionTypeId;
	private long companyId;
	private String actionNm;
	private String javaClass;
	private String command;
	private String commandArgs;
	private Long modifiedTm;
	private String modifiedBy;
	private Set<MonitorsRecoveryActions> monitorsRecoveryActionses = new HashSet<MonitorsRecoveryActions>(
			0);

	public RecoveryActions() {
	}

	public RecoveryActions(long recoveryActionId, long recoveryActionTypeId,
			long companyId, String actionNm) {
		this.recoveryActionId = recoveryActionId;
		this.recoveryActionTypeId = recoveryActionTypeId;
		this.companyId = companyId;
		this.actionNm = actionNm;
	}

	public RecoveryActions(long recoveryActionId, long recoveryActionTypeId,
			long companyId, String actionNm, String javaClass, String command,
			String commandArgs, Long modifiedTm, String modifiedBy,
			Set<MonitorsRecoveryActions> monitorsRecoveryActionses) {
		this.recoveryActionId = recoveryActionId;
		this.recoveryActionTypeId = recoveryActionTypeId;
		this.companyId = companyId;
		this.actionNm = actionNm;
		this.javaClass = javaClass;
		this.command = command;
		this.commandArgs = commandArgs;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
		this.monitorsRecoveryActionses = monitorsRecoveryActionses;
	}

	public long getRecoveryActionId() {
		return this.recoveryActionId;
	}

	public void setRecoveryActionId(long recoveryActionId) {
		this.recoveryActionId = recoveryActionId;
	}

	public long getRecoveryActionTypeId() {
		return this.recoveryActionTypeId;
	}

	public void setRecoveryActionTypeId(long recoveryActionTypeId) {
		this.recoveryActionTypeId = recoveryActionTypeId;
	}

	public long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(long companyId) {
		this.companyId = companyId;
	}

	public String getActionNm() {
		return this.actionNm;
	}

	public void setActionNm(String actionNm) {
		this.actionNm = actionNm;
	}

	public String getJavaClass() {
		return this.javaClass;
	}

	public void setJavaClass(String javaClass) {
		this.javaClass = javaClass;
	}

	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	public String getCommandArgs() {
		return this.commandArgs;
	}

	public void setCommandArgs(String commandArgs) {
		this.commandArgs = commandArgs;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<MonitorsRecoveryActions> getMonitorsRecoveryActionses() {
		return this.monitorsRecoveryActionses;
	}

	public void setMonitorsRecoveryActionses(
			Set<MonitorsRecoveryActions> monitorsRecoveryActionses) {
		this.monitorsRecoveryActionses = monitorsRecoveryActionses;
	}

}
