package com.netflexity.qflex.domain;

// Generated Jun 6, 2008 1:43:53 PM by Hibernate Tools 3.2.1.GA

/**
 * Reports generated by hbm2java
 */
public class Reports implements java.io.Serializable {

	private long reportId;
	private long reportTypeId;
	private String name;
	private String action;
	private String queryString;
	private String comments;
	private Long modifiedTm;
	private String modifiedBy;

	public Reports() {
	}

	public Reports(long reportId, long reportTypeId, String name,
			String action, String queryString) {
		this.reportId = reportId;
		this.reportTypeId = reportTypeId;
		this.name = name;
		this.action = action;
		this.queryString = queryString;
	}

	public Reports(long reportId, long reportTypeId, String name,
			String action, String queryString, String comments,
			Long modifiedTm, String modifiedBy) {
		this.reportId = reportId;
		this.reportTypeId = reportTypeId;
		this.name = name;
		this.action = action;
		this.queryString = queryString;
		this.comments = comments;
		this.modifiedTm = modifiedTm;
		this.modifiedBy = modifiedBy;
	}

	public long getReportId() {
		return this.reportId;
	}

	public void setReportId(long reportId) {
		this.reportId = reportId;
	}

	public long getReportTypeId() {
		return this.reportTypeId;
	}

	public void setReportTypeId(long reportTypeId) {
		this.reportTypeId = reportTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getQueryString() {
		return this.queryString;
	}

	public void setQueryString(String queryString) {
		this.queryString = queryString;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Long getModifiedTm() {
		return this.modifiedTm;
	}

	public void setModifiedTm(Long modifiedTm) {
		this.modifiedTm = modifiedTm;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
